### ISSUE TITLE
WH3 Schemas auto-download unavailable. 

### ISSUE THREAD

**Issue by Witchkingofdangmar** [Frodo45127/rpfm-schemas#2]
Hey Frodo, 
 I just tried to open Peacehammer after reconfiguring settings for 4.0 and encountered a problem. Despite clearing my schema folder and requesting a redownload, RPFM states that there is no update available for WH3 Schemas at this time. Thank you for your continued work.

**Comment by Frodo45127** [comment]
![imagen](https://user-images.githubusercontent.com/15714929/224478145-9170b036-6c3e-4868-8be1-e560be49acbb.png) Download this repo's files, then drop them there. Also, update to 4.0.1, 4.0 has a quite problematic bug.
